name: Docker Image Build - Push GHCR

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set release date
      run: |
        echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
      
    - name: Docker login 2
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/billhpe/dockertest:${{env.TAG}}
      
#    - name: Docker Push
#      run: docker push ghcr.io/billhpe/dockertest:${{env.TAG}}
      
  do_push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Docker login 2
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    - name: Dump GITHUB_CONTEXT
      run: echo "$GITHUB_CONTEXT"

    - name: Dump GitHub env - toJson
      env:
        GITHUB_CONTEXT2: ${{ toJson(env) }}
      run: echo "$GITHUB_CONTEXT2"

    - name: Dump GitHub context - toJson
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Docker Push
      run: docker push ghcr.io/billhpe/dockertest:${{env.TAG}}
      
