name: Docker Image Build - Push GHCR

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set release date
      run: |
        echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
      
    - name: Docker login 2
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/billhpe/dockertest:${{env.TAG}}
      
    - name: Docker Push
      run: docker push ghcr.io/billhpe/dockertest:${{env.TAG}}
      
push:
  needs: build
  runs-on: ubuntu-latest
  steps:
    -name: dump vars
      run: echo "$GITHUB_CONTEXT"
      
