name: Docker Image Build - Push GHCR

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set release date
      run: |
        echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
    
#    - name: docker login
#      env:
#        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
#        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
#      run:
#        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/dockertest:${{env.TAG}}
      
#    - name: Docker Push
#      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/dockertest:${{env.TAG}}
      
    - name: Docker login 2
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/billhpe/dockertest:${{env.TAG}}
      
    - name: Docker Push
      run: docker push ghcr.io/billhpe/dockertest:${{env.TAG}}
      
