name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set release date
      run: |
        echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/dockertest:${{env.TAG}}

    - name: Run the unit tests
      run: docker run --rm --entrypoint "/usr/local/bin/python3" ${{secrets.DOCKER_HUB_USERNAME}}/dockertest:${{env.TAG}} -m unittest test.py
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/dockertest:${{env.TAG}}
